blank_issues_enabled: false
contact_links:
  - name: ğŸ§ Miracles Journey æ•´åˆåŒ…å®˜æ–¹ QQ ç¾¤
    url: https://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=UVIuFdK5NmtT62-tM_E_EpHXdJQqZ_XB&authKey=roEf%2B4soHvUnBB4dacTvZGUiUVPntqQrbzuGFsSGmfIx5jc%2FLCO0jcn8WOQtBXwV&noverify=0&group_code=160373490
    about: è®°å¾—è¦åŠ ç¾¤å•Š! ä¸€å®šè¦åŠ å•Š!

  - name: ğŸ“œ Miracles Journey Wiki
    url: https://mjwiki.qianfuv.fun/
    about: å®˜æ–¹ Wiki , æœ‰ä¸€äº›æ•™ç¨‹å’Œå¸¸è§é—®é¢˜è§£ç­”
