name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "949892f62ffb62893dd7515b54c13b40d47cc2136d0dafc30372f5dc0fd28fe7"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
