name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045ccda5349c6686b9071f3fcb7ac85337b7b9fa709571b83c41e90882033158"

[versions]
forge = "47.4.15"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
