name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e0dad0580c85af24c31ff2c1580bf17efcced78d54c38cc9cd38cc2574e7b1"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
