name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef89bcfeea6edcd9c75fe9ba6a002d3558255cb00296cde8c0ea028f1832f82e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
