name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ccd12d982ae6496c6383f453487a6443356cef67a38830348da0a620191e6de"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
