name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b09ccaa9eb184938ff2cadde1325fec0ecc6932e19d732eb120451487698fd4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
