name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d988cc199be6ef12a405b8fc0759f522a50cc90197a8e46e86648d9355208c09"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
