name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d38780b4bdc6c4c6a3e110677a00e605e0eef7a6fd0756ec94cc512075a7bafc"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
