name = "Miracles-Journey"
author = "QianFuv"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c3a5b5d6ecd2b4c867eb842cc11342dbe2a20aab86a8bb91d1b3dde1a38d134"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
