
#Feywild General Config
[feywild]
	#The duration in ticks for the levitation effect applied by fey dust. (Minimum: 1)
	#Range: 1 ~ 100
	fey_dust_duration = 30
	#Whether players should spawn with a Feywild Lexicon
	spawn_with_lexicon = true
	#Whether fey should have voice acting on
	voices_active = true

