#
############################################
#Disabling this will force all crafted items to recieve tiers without attributes
#That would be the common tier for most items
#-------------------------------------------
#Default: true
#-------------------------------------------
"Boolean: Can Crafted Items Receive Tiers" = true
#
############################################
#Disabling this will remove the experience cost when attempting to reforge any item
#-------------------------------------------
#Default: true
#-------------------------------------------
"Boolean: Enable Reforge Experience Cost" = true
#
############################################
#
#Default: false
#-------------------------------------------
"Boolean: Can Broken Items Be Reforged" = false

