#Whether to show a toast when a player encounters a caravan.
showEncounterToast = true
#Whether to use light mode for the toast.
toastLightMode = false

[Spawning]
	#Minimum world age in ticks required before caravans can start spawning.
	#24000 ticks = 1 Minecraft day.
	#Range: > 0
	worldAgeRequired = 24000
	#Additional multiplier applied to the base cooldowns defined in the datapack.
	#Larger caravans usually have longer cooldowns after spawning.
	#This value scales all existing cooldowns globally (1.0 = 100%).
	#Range: 0.1 ~ 100.0
	cooldownMultiplier = 1.0
	#Cooldown in ticks after a failed caravan spawn attempt before trying again.
	#Range: > 200
	failedCooldown = 1200
	#Base distance from the player where caravans will spawn.
	#Range: 8 ~ 256
	distance = 32
	#Random variance added to the base spawn distance (0~value).
	#Range: 0 ~ 256
	distanceVariance = 32

